version: '3,8'

services:
  postgres:
    container_name: ticketeria
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticketeria
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres